[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "calculator_seeker747"
version = "0.1.0"
description = "A simple calculator package"
readme = "README.md"
requires-python = ">=3.7"
authors = [
  { email = "imraan.mohamedhoesein@gmail.com" }
]
license = { text = "MIT" }
keywords = ["calculator", "math", "arithmetic"]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent"
]

[project.urls]
"Homepage" = "https://github.com/Seekers747/calculator_seeker747"
"Repository" = "https://github.com/Seekers747/calculator_seeker747"
